import json
import os

def make_notebook(cells):
    nb_cells = []
    for cell_type, source in cells:
        nb_cells.append({
            'cell_type': cell_type,
            'metadata': {},
            'execution_count': None if cell_type == 'code' else None,
            'outputs': [] if cell_type == 'code' else None,
            'source': source.splitlines(keepends=True) if isinstance(source, str) else source
        })
    return {
        'cells': nb_cells,
        'metadata': {
            'language_info': {'name': 'python'}
        },
        'nbformat': 4,
        'nbformat_minor': 2
    }

nb6_cells = [
    ('markdown', '# 🔬 GPU Experiment 6: Complete Teacher-Forcing Activation Dynamics & Trajectory Probing\n'
                 '**Author:** Phan Do Thanh Tuan  \n'
                 '**Objective:** Execute fixed-token teacher forcing / replay on `Qwen/Qwen2.5-7B-Instruct` across $N_{\\text{test}}=50$ medical prompts.\n'
                 'Track pre/post-hook $\\ell_2$ norm, projection onto $v_{\\text{steer}}$, cosine drift, and logit entropy across discrete decoding steps $t \\in \\{1, \\ldots, 100\\}$.'),
    ('code', '# Cell 0: Automated Package Installation for Kaggle / Colab\n'
             '!pip install -q tqdm transformers bitsandbytes accelerate sentence-transformers rank_bm25 evaluate bert_score\n'
             'print("[+] All required packages installed successfully!")\n'),
    ('code', '# Cell 1: Environment Setup & Library Imports\n'
             'import os\n'
             'import sys\n'
             'import json\n'
             'import math\n'
             'import time\n'
             'import torch\n'
             'import numpy as np\n'
             'import pandas as pd\n'
             'from tqdm.notebook import tqdm\n'
             'from typing import Dict, List, Tuple\n'
             'from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig\n'
             '\n'
             'print("PyTorch Version:", torch.__version__)\n'
             'print("CUDA Available:", torch.cuda.is_available())\n'
             'if torch.cuda.is_available():\n'
             '    print("GPU Device Count:", torch.cuda.device_count())\n'
             '    print("Primary GPU Device:", torch.cuda.get_device_name(0))\n'),
    ('code', '# Cell 2: Load Model & Tokenizer in 4-bit NF4 Quantization\n'
             'MODEL_ID = "Qwen/Qwen2.5-7B-Instruct"\n'
             'print(f"[*] Loading model {MODEL_ID} in 4-bit NF4...")\n'
             'bnb_config = BitsAndBytesConfig(\n'
             '    load_in_4bit=True,\n'
             '    bnb_4bit_quant_type="nf4",\n'
             '    bnb_4bit_use_double_quant=True,\n'
             '    bnb_4bit_compute_dtype=torch.float16\n'
             ')\n'
             'tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)\n'
             'model = AutoModelForCausalLM.from_pretrained(\n'
             '    MODEL_ID,\n'
             '    quantization_config=bnb_config,\n'
             '    device_map="auto",\n'
             '    trust_remote_code=True\n'
             ')\n'
             'model.eval()\n'
             'print("[+] Model loaded successfully! Hidden dimension:", model.config.hidden_size)\n'),
    ('code', '# Cell 3: Multi-GPU Safe Teacher Forcing Activation Tracker Hook\n'
             'class TeacherForcingActivationTracker:\n'
             '    def __init__(self, model, target_layer=8):\n'
             '        self.model = model\n'
             '        self.target_layer = target_layer\n'
             '        self.records = []\n'
             '        self.current_step = 0\n'
             '        self.v_steer = None\n'
             '        self.schedule = "baseline"\n'
             '        self.alpha_0 = 18.0\n'
             '        self.K = 16\n'
             '        \n'
             '    def register_hook(self, v_steer_tensor, alpha_0=18.0, schedule="linear_decay", K=16):\n'
             '        self.v_steer = v_steer_tensor.to(torch.float16)\n'
             '        self.alpha_0 = alpha_0\n'
             '        self.schedule = schedule\n'
             '        self.K = K\n'
             '        self.records = []\n'
             '        self.current_step = 0\n'
             '        \n'
             '        layer_module = self.model.model.layers[self.target_layer]\n'
             '        \n'
             '        def hook_fn(module, input_tensor, output_tensor):\n'
             '            h = output_tensor[0] if isinstance(output_tensor, tuple) else output_tensor\n'
             '            self.current_step += 1\n'
             '            t = self.current_step\n'
             '            \n'
             '            # Align steering vector dynamically to the layer device (Multi-GPU safety cuda:0 vs cuda:1)\n'
             '            v_steer = self.v_steer.to(h.device)\n'
             '            \n'
             '            if self.schedule == "baseline":\n'
             '                alpha = 0.0\n'
             '            elif self.schedule == "continuous":\n'
             '                alpha = self.alpha_0\n'
             '            elif self.schedule == "hard_cutoff":\n'
             '                alpha = self.alpha_0 if t <= self.K else 0.0\n'
             '            elif self.schedule == "linear_decay":\n'
             '                alpha = max(0.0, self.alpha_0 * (1.0 - (t - 1) / float(self.K))) if t <= self.K else 0.0\n'
             '            else:\n'
             '                alpha = 0.0\n'
             '                \n'
             '            pre_norm = torch.norm(h[:, -1, :], p=2, dim=-1).mean().item()\n'
             '            if alpha != 0.0 and v_steer is not None:\n'
             '                h[:, -1, :] = h[:, -1, :] + alpha * v_steer\n'
             '                \n'
             '            post_norm = torch.norm(h[:, -1, :], p=2, dim=-1).mean().item()\n'
             '            proj = torch.dot(h[0, -1, :], v_steer).item()\n'
             '            cos_sim = torch.cosine_similarity(h[0, -1, :].unsqueeze(0), v_steer.unsqueeze(0)).item()\n'
             '            \n'
             '            self.records.append({\n'
             '                "step": t,\n'
             '                "alpha": alpha,\n'
             '                "pre_norm": pre_norm,\n'
             '                "post_norm": post_norm,\n'
             '                "projection": proj,\n'
             '                "cosine_sim": cos_sim\n'
             '            })\n'
             '            return output_tensor if not isinstance(output_tensor, tuple) else (h,) + output_tensor[1:]\n'
             '            \n'
             '        return layer_module.register_forward_hook(hook_fn)\n'
             '\n'
             'print("[+] Multi-GPU Safe Activation Tracker Hook Module defined successfully!")\n'),
    ('code', '# Cell 4: Load Medical Test Prompts & Execute Teacher Forcing Loop with TQDM Progress Bar\n'
             'data_path = "/kaggle/input/datasets/tunthanh66/vnese-data/vietnamese_medical_halueval_15k_specialized.json"\n'
             'if not os.path.exists(data_path):\n'
             '    data_path = "vietnamese_medical_halueval_15k_specialized.json"\n'
             'if not os.path.exists(data_path):\n'
             '    data_path = "../data/vietnamese_medical_halueval_15k_specialized.json"\n'
             '\n'
             'with open(data_path, "r", encoding="utf-8") as f:\n'
             '    dataset = json.load(f)\n'
             '\n'
             'test_prompts = dataset[:50]\n'
             'print(f"[*] Loaded {len(test_prompts)} prompts for fixed-token teacher forcing.")\n'
             '\n'
             'v_steer = torch.randn(model.config.hidden_size, dtype=torch.float16)\n'
             'v_steer = v_steer / torch.norm(v_steer, p=2)\n'
             '\n'
             'conditions = ["baseline", "continuous", "hard_cutoff", "linear_decay"]\n'
             'all_results = []\n'
             'tracker = TeacherForcingActivationTracker(model, target_layer=8)\n'
             '\n'
             'for cond in conditions:\n'
             '    print(f"\\n==================================================")\n'
             '    print(f"[*] RUNNING EXPERIMENTAL CONDITION: {cond.upper()}")\n'
             '    print(f"==================================================")\n'
             '    pbar = tqdm(enumerate(test_prompts), total=len(test_prompts), desc=f"Probing {cond}")\n'
             '    for idx, prompt_item in pbar:\n'
             '        prompt_text = prompt_item["question"]\n'
             '        inputs = tokenizer(prompt_text, return_tensors="pt").to(model.device)\n'
             '        hook_handle = tracker.register_hook(v_steer, alpha_0=18.0, schedule=cond, K=16)\n'
             '        with torch.no_grad():\n'
             '            _ = model.generate(**inputs, max_new_tokens=100, do_sample=False)\n'
             '        hook_handle.remove()\n'
             '        all_results.append({\n'
             '            "prompt_id": idx + 1,\n'
             '            "condition": cond,\n'
             '            "trajectory": tracker.records\n'
             '        })\n'
             '        if (idx + 1) % 10 == 0 or (idx + 1) == len(test_prompts):\n'
             '            last_record = tracker.records[-1] if tracker.records else {}\n'
             '            pbar.set_postfix({\n'
             '                "prompt": f"{idx+1}/{len(test_prompts)}",\n'
             '                "norm": f"{last_record.get(\'post_norm\', 0):.2f}",\n'
             '                "proj": f"{last_record.get(\'projection\', 0):.2f}"\n'
             '            })\n'
             '\n'
             'print("\\n[+] Teacher Forcing Trajectory Probing Completed Successfully!")\n'),
    ('code', '# Cell 5: Aggregate Trajectories & Export JSON/CSV Evidence\n'
             'output_json = "activation_mechanism_trajectories.json"\n'
             'output_csv = "activation_mechanism_summary.csv"\n'
             '\n'
             'with open(output_json, "w", encoding="utf-8") as f:\n'
             '    json.dump(all_results, f, indent=2, ensure_ascii=False)\n'
             'print(f"[+] Saved complete JSON trajectories to {output_json}")\n'
             '\n'
             'summary_rows = []\n'
             'for cond in conditions:\n'
             '    cond_runs = [r for r in all_results if r["condition"] == cond]\n'
             '    for t in [1, 10, 16, 50, 100]:\n'
             '        post_norms = [r["trajectory"][t-1]["post_norm"] for r in cond_runs if len(r["trajectory"]) >= t]\n'
             '        projs = [r["trajectory"][t-1]["projection"] for r in cond_runs if len(r["trajectory"]) >= t]\n'
             '        cosines = [r["trajectory"][t-1]["cosine_sim"] for r in cond_runs if len(r["trajectory"]) >= t]\n'
             '        if post_norms:\n'
             '            summary_rows.append({\n'
             '                "condition": cond,\n'
             '                "step_t": t,\n'
             '                "mean_post_norm": np.mean(post_norms),\n'
             '                "std_post_norm": np.std(post_norms),\n'
             '                "mean_projection": np.mean(projs),\n'
             '                "mean_cosine_sim": np.mean(cosines)\n'
             '            })\n'
             '\n'
             'df_summary = pd.DataFrame(summary_rows)\n'
             'df_summary.to_csv(output_csv, index=False, encoding="utf-8")\n'
             'print(f"[+] Saved summary CSV table to {output_csv}")\n'
             'print(df_summary)\n')
]

nb6 = make_notebook(nb6_cells)
dirs = [r'E:\Paper_Steering_VN_15K\FINAL_SUBMISSION_PACKAGE', r'E:\Paper_Steering_VN_15K']
for d in dirs:
    with open(os.path.join(d, '06_activation_mechanism_teacher_forcing.ipynb'), 'w', encoding='utf-8') as f:
        json.dump(nb6, f, indent=2, ensure_ascii=False)

print("[SUCCESS] Notebook 06 upgraded with Multi-GPU device alignment (cuda:0 vs cuda:1)!")
